(define (problem agencia_viaje)
    (:domain agencia_viaje)
    (:objects
        cg1  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10   - ciudad
        vg1  v1  v2  v3  v4  v5  v6  v7  v8  v9  v10  v11  v12  v13  v14  v15   - vuelo
        h1  h2  h3  h4  h5  h6  h7  h8  h9  h10  h11  h12  h13  h14  h15  - hotel
        dias2  dias3  dias4  - dias_por_ciudad
    )
    (:init
        (= (num_ciudades_escogidas) 0)
        (= (min_ciudades_a_recoger) 7 )
        (= (min_dias_por_ciudad) 2 )
        (= (max_dias_por_ciudad) 4 )
        (= (num_dias_recorrido) 0)
        (= (min_dias_recorrido) 10 )
        (= (dias_por_ciudad dias2) 2)
        (= (dias_por_ciudad dias3) 3)
        (= (dias_por_ciudad dias4) 4)
        (= (min_precio_plan) 200)
        (= (max_precio_plan) 3000)
        (= (precio_plan) 0)
        (current_ciudad cg1)
        (ciudad_visitada cg1)
        (va_a vg1 cg1 c1)
        (va_a vg1 cg1 c2)
        (va_a vg1 cg1 c3)
        (va_a vg1 cg1 c4)
        (va_a vg1 cg1 c5)
        (va_a vg1 cg1 c6)
        (va_a vg1 cg1 c7)
        (va_a vg1 cg1 c8)
        (va_a vg1 cg1 c9)
        (va_a vg1 cg1 c10)
        (va_a v1 c4 c3 )
        (va_a v2 c3 c6 )
        (va_a v3 c6 c1 )
        (va_a v4 c1 c7 )
        (va_a v5 c7 c10 )
        (va_a v6 c10 c5 )
        (va_a v7 c5 c8 )
        (va_a v8 c8 c9 )
        (va_a v9 c9 c2 )
        (va_a v10 c2 c4 )
        (va_a v11 c10 c4 )
        (va_a v12 c4 c2 )
        (va_a v13 c2 c6 )
        (va_a v14 c6 c1 )
        (va_a v15 c1 c7 )
        (esta_en h1 c9 )
        (esta_en h2 c10 )
        (esta_en h3 c4 )
        (esta_en h4 c2 )
        (esta_en h5 c6 )
        (esta_en h6 c1 )
        (esta_en h7 c7 )
        (esta_en h8 c5 )
        (esta_en h9 c3 )
        (esta_en h10 c8 )
        (esta_en h11 c9 )
        (esta_en h12 c10 )
        (esta_en h13 c4 )
        (esta_en h14 c2 )
        (esta_en h15 c6 )
        (= (precio_hotel h1) 37)
        (= (precio_hotel h2) 221)
        (= (precio_hotel h3) 31)
        (= (precio_hotel h4) 201)
        (= (precio_hotel h5) 241)
        (= (precio_hotel h6) 87)
        (= (precio_hotel h7) 79)
        (= (precio_hotel h8) 257)
        (= (precio_hotel h9) 137)
        (= (precio_hotel h10) 44)
        (= (precio_hotel h11) 71)
        (= (precio_hotel h12) 95)
        (= (precio_hotel h13) 217)
        (= (precio_hotel h14) 298)
        (= (precio_hotel h15) 250)
        (= (precio_vuelo v1) 83)
        (= (precio_vuelo v2) 160)
        (= (precio_vuelo v3) 43)
        (= (precio_vuelo v4) 154)
        (= (precio_vuelo v5) 198)
        (= (precio_vuelo v6) 194)
        (= (precio_vuelo v7) 101)
        (= (precio_vuelo v8) 154)
        (= (precio_vuelo v9) 55)
        (= (precio_vuelo v10) 55)
        (= (precio_vuelo v11) 262)
        (= (precio_vuelo v12) 77)
        (= (precio_vuelo v13) 119)
        (= (precio_vuelo v14) 68)
        (= (precio_vuelo v15) 219)
        (= (precio_vuelo vg1) 0)
 
    )
        
    (:goal (and
        (<= (min_precio_plan) (precio_plan))
        (>= (max_precio_plan) (precio_plan))
        (<= (min_ciudades_a_recoger) (num_ciudades_escogidas))
        (<= (min_dias_recorrido) (num_dias_recorrido))
    ))
    ;; maximize negativo minimize negativo o viceversa
    ;; minimize va DESPUES del goal
    (:metric minimize 
        (precio_plan)
    )
)