(define (problem agencia_viaje)
    (:domain agencia_viaje)
    (:objects
        cg1  c1  c2  c3  c4  c5  c6   - ciudad
        vg1  v1  v2  v3  v4  v5  v6  v7  v8  v9  v10  v11  v12  v13  v14  v15  v16  v17  v18  v19  v20  v21   - vuelo
        h1  h2  h3  h4  h5  h6  h7  h8  h9  h10  h11  h12  h13  h14  h15  h16  h17  h18  h19  h20  - hotel
        dias2  dias3  dias4  dias5  dias6  dias7  dias8  - dias_por_ciudad
    )
    (:init
        (= (num_ciudades_escogidas) 0)
        (= (min_ciudades_a_recoger) 3 )
        (= (min_dias_por_ciudad) 2 )
        (= (max_dias_por_ciudad) 8 )
        (= (num_dias_recorrido) 0)
        (= (min_dias_recorrido) 10 )
        (= (dias_por_ciudad dias2) 2)
        (= (dias_por_ciudad dias3) 3)
        (= (dias_por_ciudad dias4) 4)
        (= (dias_por_ciudad dias5) 5)
        (= (dias_por_ciudad dias6) 6)
        (= (dias_por_ciudad dias7) 7)
        (= (dias_por_ciudad dias8) 8)
         (= (interes_actual) 0)
        (= (interes_ciudad cg1) 6)
        (= (interes_ciudad c1) 1)
        (= (interes_ciudad c2) 4)
        (= (interes_ciudad c3) 6)
        (= (interes_ciudad c4) 6)
        (= (interes_ciudad c5) 0)
        (current_ciudad cg1)
        (= (interes_ciudad cg1) 0)
        (ciudad_visitada cg1)
        (va_a vg1 cg1 c1)
        (va_a vg1 cg1 c2)
        (va_a vg1 cg1 c3)
        (va_a vg1 cg1 c4)
        (va_a vg1 cg1 c5)
        (va_a vg1 cg1 c6)
        (va_a v1 c3 c2 )
        (va_a v2 c2 c5 )
        (va_a v3 c5 c4 )
        (va_a v4 c4 c6 )
        (va_a v5 c6 c1 )
        (va_a v6 c1 c3 )
        (va_a v7 c3 c2 )
        (va_a v8 c2 c5 )
        (va_a v9 c5 c4 )
        (va_a v10 c4 c6 )
        (va_a v11 c6 c1 )
        (va_a v12 c1 c3 )
        (va_a v13 c3 c2 )
        (va_a v14 c2 c5 )
        (va_a v15 c5 c4 )
        (va_a v16 c4 c6 )
        (va_a v17 c6 c1 )
        (va_a v18 c1 c3 )
        (va_a v19 c3 c2 )
        (va_a v20 c2 c5 )
        (va_a v21 c5 c4 )
        (esta_en h1 c1 )
        (esta_en h2 c3 )
        (esta_en h3 c2 )
        (esta_en h4 c5 )
        (esta_en h5 c4 )
        (esta_en h6 c6 )
        (esta_en h7 c1 )
        (esta_en h8 c3 )
        (esta_en h9 c2 )
        (esta_en h10 c5 )
        (esta_en h11 c4 )
        (esta_en h12 c6 )
        (esta_en h13 c1 )
        (esta_en h14 c3 )
        (esta_en h15 c2 )
        (esta_en h16 c5 )
        (esta_en h17 c4 )
        (esta_en h18 c6 )
        (esta_en h19 c1 )
        (esta_en h20 c3 )
 
    )
        
    (:goal (and
    (<= (min_ciudades_a_recoger) (num_ciudades_escogidas))
    ))
    ;; maximize negativo minimize negativo o viceversa
	;; minimize va DESPUES del goal
	(:metric minimize 
		(interes_actual)
	)
)
